# -*- coding: utf-8 -*-
"""Brooke_Johnson_Homework 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yGwpYFGMvnaVdORVEiscUsUHY0QdA4A3

# Homework 1 (100 points)

**The very first thing you should do is save your own copy of this Homework by clicking on File -> "Save a copy in Drive"**

This homework is divided into 3 sections which all perform different tasks on the initial data provided.  Read the data description below carefully to understand the data, then work on each section.

When you complete this assignment, **please submit 1 file and 1 link via Canvas before the deadline.**


1.   Your Jupyter Notebook code as a .py file (File -> "Download .py")
2.   As a comment on your .py submission please include a link to your Google CoLab Jupyter notebook. Click the "Share" button in the top right.  Ensure that anyone with the link has at least "Commenter" access. **Once you submit your HW on Canvas, please do not make any more edits to the Jupyter notebook until after your HW is graded**

For the .py file, please use the naming convention:  

**firstname_lastname_homework1.py**

## Data Description

The data below represents average daily temperatures for the month of August 2000 are provided below for 7 major European cities.  Thus, each city-named variable is assigned a list of 31 values, one for every day in the month of August.  They are sequential, so the first value represents the average daily temperature on August 1 and the last value represents the average daily temperature on August 31.  

In other words, the data format is:

`city_name = [august1_temp, august2_temp, ... , august31_temp]`

Run the code block to load the data.  Then use this data to answer questions 1 and 2.
"""

# Each data point represents one day in the month of August 2000. 
# e.g. the first data point was the avg daily temperature on August 1, 2000
paris = [75.9, 67.2, 64.2, 63.3, 65.5, 67.0, 70.3, 68.1, 70.9, 68.0, 69.9, 74.0, 77.1, 74.1, 70.0, 69.8, 69.9, 67.9, 65.9, 63.3, 62.4, 63.8, 68.6, 73.3, 75.8, 70.7, 63.5, 64.6, 66.4, 66.4, 65.3]
helsinki = [60.2, 62.1, 61.7, 61.7, 60.2, 62.7, 61.9, 58.6, 56.8, 59.8, 59.9, 61.8, 63.0, 63.9, 60.1, 64.5, 59.5, 57.4, 60.3, 60.2, 60.4, 58.9, 54.6, 54.3, 57.2, 58.9, 58.5, 59.0, 59.2, 61.1, 60.9]
copenhagen = [61.2, 62.4, 60.6, 60.6, 59.0, 61.5, 57.6, 57.5, 58.8, 57.5, 60.5, 59.5, 58.6, 61.7, 65.5, 60.6, 60.2, 60.5, 60.3, 60.9, 57.4, 56.2, 56.3, 55.9, 57.9, 58.4, 62.0, 61.0, 61.8, 57.6, 55.5]
rome = [73.9, 73.5, 73.6, 75.2, 71.8, 70.0, 71.4, 73.7, 73.3, 74.5, 74.9, 74.4, 79.5, 76.0, 76.8, 78.3, 77.1, 77.4, 76.4, 77.2, 77.9, 78.7, 79.6, 79.9, 77.6, 78.4, 77.8, 77.4, 76.5, 73.8, 74.9]
madrid = [83.8, 83.8, 73.6, 67.9, 68.0, 70.5, 73.2, 75.0, 78.7, 81.2, 76.7, 74.8, 78.7, 78.7, 84.6, 83.9, 83.6, 82.3, 79.3, 75.7, 73.6, 68.6, 68.8, 73.9, 76.0, 71.9, 71.8, 73.8, 77.3, 75.9, 71.7]
stockholm = [65.9, 62.7, 60.5, 63.9, 63.9, 63.9, 61.0, 58.1, 62.5, 63.1, 64.1, 63.6, 61.3, 64.4, 65.3, 63.6, 62.6, 62.1, 63.3, 60.3, 61.1, 59.4, 57.5, 54.7, 57.0, 61.4, 62.1, 62.4, 62.7, 61.0, 56.5]
london = [66.6, 63.1, 61.3, 63.9, 65.1, 68.7, 68.0, 66.8, 65.4, 67.8, 67.6, 68.8, 65.9, 67.6, 65.6, 65.6, 63.0, 62.2, 64.9, 63.4, 60.8, 62.4, 64.8, 67.8, 68.3, 65.7, 61.5, 60.4, 61.2, 62.3, 61.1]

"""## Section 1 - Summary Stats

**Value: 25 points (5 points per question)**

Using `numpy` load the data into `numpy` arrays. Include the code and use a print statement to print the answers.

1.   What are the mean, min, and max temperatures of Paris?
2.   What is the minimum and maximum temperature in Europe (from the 7 cities provided) for the month of August?
3.   Which city had the greatest range of temperatures in August (max - min)?  What was it?
4.   Which city had the smallest range of temperatures in August (max - min)?  What was it?
5.   Output an array with the daily average temperature of the 7 cities for the month.  The resulting array should have 31 elements in it, one for each day, with each data point representing the mean of the 7 daily temperatures for that day.




"""

import numpy as np
temperatures = np.array(
    [
     paris,
     helsinki,
     copenhagen,
     rome,
     madrid,
     stockholm,
     london,
     ]
)

# 1 Write code and answer below
paris_mean = np.mean(paris)
paris_min = np.min(paris)
paris_max = np.max(paris)
print(paris_mean)
print(paris_min)
print(paris_max)

# 2 Write code and answer below
europe_min = np.min(temperatures)
europe_max = np.max(temperatures)
print(europe_min)
print(europe_max)

# 3 & 4 Write code and answer below
paris_range = np.max(paris) - np.min(paris)
helsinki_range = np.max(helsinki) - np.min(helsinki)
copenhagen_range = np.max(copenhagen) - np.min(copenhagen)
madrid_range = np.max(madrid) - np.min(madrid)
rome_range = np.max(rome) - np.min(rome)
london_range = np.max(london) - np.min(london)
stockholm_range = np.max(stockholm) - np.min(stockholm)

range_list = [paris_range, helsinki_range, copenhagen_range, madrid_range, rome_range, london_range, stockholm_range]
biggest_range = 0
for range in range_list:
  if range > biggest_range:
    biggest_range = range
print(biggest_range)

smallest_range = 100
for range in range_list:
  if range < smallest_range:
    smallest_range = range
print(smallest_range)

#alternative solution to #3 & #4
range_max = np.max(range_list)
print(range_max)
range_min = np.min(range_list)
print(range_min)

# 5 Write code and answer below
ave_daily = np.average(temperatures, axis=0) [0:30]
print (ave_daily)

"""## Section 2 - Data Transformation
**Value: 50 points total**

**Part 1 (15 points)**
Numbers are useful, but sometimes we can extract more insight from data if we find a way to group or categorize the numbers in a meaningful way.  For the temperature data, let's group this data into temperature categories as defined below.

---


80+ degrees: "Hot"

70 <= x < 80 degrees:  "Warm"

60 <= x < 70 degrees:  "Cool"

Less than 60 degrees:  "Cold"


---


**Pick one city**, iterate through the temperature array and create a new array or list that contains the categories above based on the avg daily temperature.

The output should thus be an array (or list) that has 31 elements.  Each element is a string that is either `"Hot"`, `"Warm"`, `"Cool"` or `"Cold"`. Let's name this new array `cityname_temperature_categories` where `cityname` should be replaced with the city you chose.

Example:  The first few values of `paris_temperature_categories` would be `["Warm", "Cool", "Cool", "Cool" ... ]`

*Hint: Use `if` and `elif` statements combined with one or more `for` loops.*

*Challenge: For a challenge (not required), find a way to scale your transformation solution to all 7 cities, perhaps using loops or functions*

"""

# Write code below. 

paris_temperature_categories = paris
my_list = []
for temperature in paris:
    if temperature >= 80:
      paris_temperature_categories = "Hot"
    elif temperature >= 70 and temperature <80:
      paris_temperature_categories = "Warm"
    elif temperature >=60 and temperature <70:
      paris_temperature_categories = "Cool"
    elif temperature <60:
      paris_temperature_categories = "Cold"
    my_list.append(paris_temperature_categories)
    my_array = np.array(my_list)
print(my_array)


# Print your output array below

"""**Part 2 (20 points)**

Suppose we want to better understand how the temperatures fluctuate from day to day.  **Pick one city (can be the same city as part 1)** and let's create a new array (or list) that measures the delta between the temperature on **day** and **day+1**.  

This should result in a an array/list with 30 elements in it.  The first element (at index 0) would be the temperature delta August 2 - August 1, the second element (at index 1) would be August 3 - August 2, and so on until the final element is August 31 - August 30. Let's name this new array `cityname_daily_deltas` where `cityname` should be replaced with the city you chose.

Example: The first few values of `paris_daily_deltas` would be `[-8.7, -3. , -0.9,  2.2 ... ]`


*Hint:  There are multiple ways to accomplish this. Feel free to choose whichever way you are most comfortable with.  One way could involve creating a new list by looping through the original list.  Another way could involve copying and slicing arrays, then element-wise subtracting.*

*Challenge: For a challenge (not required), find a way to scale your transformation solution to all 7 cities, perhaps using loops or functions*



"""

# Write code below. 

days1 = np.array(paris[0:29])
days2 = np.array(paris[1:30])
paris_daily_deltas = days2-days1
print(paris_daily_deltas)

# Print your output array below

"""**Part 3 (15 points)**

Now, we want to translate the deltas in the delta arrays we created in Part 2 from numeric values into text categories.  Using the following definitions, create new arrays (or lists) that contain the given text string translation of the numeric value.  

The result should be an arrays with 30 elements, as we are simply transforming the numeric values into text categories. Let's name this new array `cityname_daily_delta_categories` where `cityname` should be replaced with the city you chose in part 2.

Example: The first few values of `paris_daily_delta_categories` would be ["large_decrease", "small_decrease" , "no_significant_change", "small_increase" ... ]

---


x >= 7     : "large_increase"

3 <= x < 7 : "medium_increase"

1 <= x < 3 : "small_increase" 

-1 <= x < 1 : "no_significant_change"

-3 <= x < -1 : "small_decrease"

-7 <= x < -3 : "medium_decrease"

x < -7       : "large_decrease"


---

*Challenge: For a challenge (not required), find a way to scale your transformation solution to all 7 cities, perhaps using loops or functions*


"""

# Write your code below. 

new_result = paris_daily_deltas
new_list = []
for item in paris_daily_deltas:
    if item >= 7:
      new_result = "large_increase"
    elif item >= 3 and item <7:
      new_result = "medium_increase"
    elif item >=1 and item <3:
      new_result = "small_increase"
    elif item >=-1 and item <1:
      new_result = "no_significant_change"      
    elif item >=-3 and item <1:
      new_result = "small_decrease"
    elif item >=-7 and item <-1:
      new_result = "medium_decrease"
    elif item <-7:
      new_result = "large_decrease"
    new_list.append(new_result)
    paris_daily_delta_categories = np.array(new_list)
print(paris_daily_delta_categories)

# Print your output array below

"""## Section 3 - Histogram
**Value: 25 points (10 points for writing the function, 10 points for passing all test cases, 5 points for running your function on the arrays from section 2)**

Write a **function** to create a histogram (a frequency distribution) of an arbitrary list of input values.  The function will take in as input a **list** of values, and return a dictionary with **keys** representing each value in the input list and **values** representing the frequency with which they appear in the input list.

For example, given input `["M", "F", "F", "F, "M"]`, the function should return `{"M": 2, "F": 3}` as there are two "M" and three "F" in the input list.

*Hint:  For every value you process, you will need to consider whether you need to add a new key to the output dictionary `histogram` or increment the stored count for an existing key.* 
"""

mylist = ["k", "j", "d", "h", "f", "k", "h", "c", "l", "k"]

def create_histogram(input_list) -> dict:
    histogram = {}
    for index in input_list:
      histogram[index] = histogram.get(index,0)+1
    return histogram

myhistogram = create_histogram(mylist)
print(myhistogram)

# Below are a few test cases. Don't modify the code below. Simply run this code block.
# If you get an assertion error, this means that at least one of the test cases is failing.
# If it gets to the print statement, this means that all tests have passed

assert(create_histogram([1,1,1,1,1,1,1,1,1,2]) == {1:9, 2:1})
print("Passed first test case")
assert(create_histogram(["black", "blue", "yellow", "black", "blue", "red", "", "green"]) == {'': 1, 'black': 2, 'blue': 2, 'green': 1, 'red': 1, 'yellow': 1})
print("Passed second test case")
assert(create_histogram([l for l in "how many of each letter are in this sentence"]) == 
{' ': 8,
 'a': 3,
 'c': 2,
 'e': 7,
 'f': 1,
 'h': 3,
 'i': 2,
 'l': 1,
 'm': 1,
 'n': 4,
 'o': 2,
 'r': 2,
 's': 2,
 't': 4,
 'w': 1,
 'y': 1})
print("Passed third test case")
print("Passes all tests")

"""**Putting it all together**

Try running your new `create_histogram` function on the arrays you created from Section 2 to see the frequency distribution of the categories you defined.  

*Side Note: If you took the challenge to scale your solutions to all 7 cities, it would be especially interesting to compare the relative distributions of the temperature categories and delta categories across cities.*
"""

# Pass the arrays you created in Section 2 into your `create_histogram` function

# Histogram of the Paris temperature categories:
paris_temp_category_histogram = create_histogram(my_array)
print(paris_temp_category_histogram)

# Histogram of the Paris temperature deltas:
paris_temp_delta_histogram = create_histogram(paris_daily_deltas)
print(paris_temp_delta_histogram)

# Histogram of the Paris delta categories:
paris_delta_category_histogram = create_histogram(paris_daily_delta_categories)
print(paris_delta_category_histogram)